package com.qwe7002.telegram_sms.data_structure

import com.google.gson.annotations.SerializedName

/**
 * Data structure for output-metadata.json generated by Android Gradle Plugin
 * Used to determine app updates based on versionCode
 */
data class OutputMetadata(
    val version: Int,
    val artifactType: ArtifactType,
    val applicationId: String,
    val variantName: String,
    val elements: List<Element>
)

data class ArtifactType(
    val type: String,
    val kind: String
)

data class Element(
    val type: String,
    @SerializedName("versionCode")
    val versionCode: Int,
    @SerializedName("versionName")
    val versionName: String,
    val enabled: Boolean,
    val outputFile: String
)

