package com.qwe7002.telegram_sms.data_structure

import com.google.gson.Gson
import com.google.gson.JsonParser
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Wire-format contract for [ScannerJson], the config blob exchanged between devices
 * through the QR scanner (`MainActivity`) and `TransferConfigActivity`.
 *
 * This format crosses app versions: a QR generated by an older build gets parsed by a
 * newer one and vice versa. So what matters is the key names and, for the fields added
 * later, that "absent" stays distinguishable from "explicitly false".
 */
class ScannerJsonTest {

    private val gson = Gson()

    private fun sample(
        ccService: ArrayList<CcSendService>? = null,
        dohSwitch: Boolean? = null
    ) = ScannerJson(
        botToken = "123456:ABC-DEF",
        apiAddress = "api.telegram.org",
        chatId = "-1001234567890",
        trustedPhoneNumber = "+8615905698105",
        batteryMonitoringSwitch = true,
        chargerStatus = false,
        chatCommand = true,
        fallbackSms = false,
        privacyMode = true,
        verificationCode = false,
        callNotifySwitch = true,
        topicID = "42",
        ccService = ccService,
        hidePhoneNumber = false,
        dohSwitch = dohSwitch
    )

    @Test
    fun serializesTheDocumentedSnakeCaseKeys() {
        val json = JsonParser.parseString(gson.toJson(sample(dohSwitch = true))).asJsonObject

        assertEquals("123456:ABC-DEF", json["bot_token"].asString)
        assertEquals("api.telegram.org", json["api_address"].asString)
        assertEquals("-1001234567890", json["chat_id"].asString)
        assertEquals("+8615905698105", json["trusted_phone_number"].asString)
        assertTrue(json["battery_monitoring_switch"].asBoolean)
        assertFalse(json["charger_status"].asBoolean)
        assertTrue(json["chat_command"].asBoolean)
        assertFalse(json["fallback_sms"].asBoolean)
        assertTrue(json["privacy_mode"].asBoolean)
        assertFalse(json["verification_code"].asBoolean)
        assertTrue(json["call_notify"].asBoolean)
        assertEquals("42", json["topic_id"].asString)
        assertFalse(json["hide_phone_number"].asBoolean)
        assertTrue(json["doh_switch"].asBoolean)

        for (camel in listOf(
            "botToken", "apiAddress", "chatId", "trustedPhoneNumber",
            "batteryMonitoringSwitch", "chargerStatus", "chatCommand", "fallbackSms",
            "privacyMode", "verificationCode", "callNotifySwitch", "topicID",
            "ccService", "hidePhoneNumber", "dohSwitch"
        )) {
            assertFalse("unexpected camelCase key '$camel'", json.has(camel))
        }
    }

    @Test
    fun falseSwitchesStayOnTheWire() {
        // Importing a config has to be able to turn a switch off, so `false` must be
        // serialized rather than omitted as a default.
        val json = JsonParser.parseString(gson.toJson(sample())).asJsonObject
        assertTrue(json.has("charger_status"))
        assertTrue(json.has("fallback_sms"))
        assertTrue(json.has("verification_code"))
        assertTrue(json.has("hide_phone_number"))
    }

    @Test
    fun roundTripsThroughJson() {
        val original = sample(dohSwitch = false)
        val parsed = gson.fromJson(gson.toJson(original), ScannerJson::class.java)
        assertEquals(original, parsed)
    }

    /**
     * `doh_switch` is nullable precisely so a config produced before the field existed
     * can be told apart from one that explicitly disables DoH: null means "keep the
     * local setting", false means "turn it off". Gson does not apply the Kotlin default,
     * so an absent key really does arrive as null.
     */
    @Test
    fun absentDohSwitchParsesAsNull_notAsFalse() {
        val legacy = gson.fromJson(
            """
            {"bot_token":"t","api_address":"api.telegram.org","chat_id":"1",
             "trusted_phone_number":"","battery_monitoring_switch":false,
             "charger_status":false,"chat_command":false,"fallback_sms":false,
             "privacy_mode":false,"verification_code":false,"call_notify":false,
             "topic_id":"","hide_phone_number":false}
            """.trimIndent(),
            ScannerJson::class.java
        )
        assertNull(legacy.dohSwitch)
        assertNull(legacy.ccService)
    }

    @Test
    fun explicitFalseDohSwitchIsPreserved() {
        val parsed = gson.fromJson(
            gson.toJson(sample(dohSwitch = false)),
            ScannerJson::class.java
        )
        assertEquals(false, parsed.dohSwitch)
    }

    @Test
    fun carbonCopyServicesUseTheSnakeCaseKeyInBothDirections() {
        // The camelCase sweep above runs with ccService == null, so the key is absent and
        // proves nothing about it; and a round trip through one Gson mapping would still
        // pass if @SerializedName("cc_service") were dropped from both directions. This
        // asserts the wire key itself, then reads an explicit fixture back.
        val config = sample(ccService = arrayListOf(CcSendService("bark", true, minimalHar())))
        val json = JsonParser.parseString(gson.toJson(config)).asJsonObject
        assertTrue(json.has("cc_service"))
        assertFalse(json.has("ccService"))
        assertEquals("bark", json["cc_service"].asJsonArray[0].asJsonObject["name"].asString)

        val parsed = gson.fromJson(
            """
            {"bot_token":"t","api_address":"a","chat_id":"1","trusted_phone_number":"",
             "battery_monitoring_switch":false,"charger_status":false,"chat_command":false,
             "fallback_sms":false,"privacy_mode":false,"verification_code":false,
             "call_notify":false,"topic_id":"","hide_phone_number":false,
             "cc_service":[{"name":"gotify","enabled":false,
               "har":{"log":{"version":"1.2","entries":[]}}}]}
            """.trimIndent(),
            ScannerJson::class.java
        )
        assertNotNull(parsed.ccService)
        assertEquals("gotify", parsed.ccService!![0].name)
        assertFalse(parsed.ccService!![0].enabled)
    }

    private fun minimalHar(): HAR = gson.fromJson(
        """
        {"log":{"version":"1.2","entries":[{"request":{
          "method":"GET","url":"https://push.example/send","httpVersion":"HTTP/1.1",
          "cookies":[],"headers":[],"queryString":[],"headersSize":-1,"bodySize":0}}]}}
        """.trimIndent(),
        HAR::class.java
    )

    @Test
    fun carriesCarbonCopyServicesWhenPresent() {
        val config = sample(ccService = arrayListOf(CcSendService("bark", true, minimalHar())))

        val parsed = gson.fromJson(gson.toJson(config), ScannerJson::class.java)
        assertNotNull(parsed.ccService)
        assertEquals(1, parsed.ccService!!.size)
        assertEquals("bark", parsed.ccService!![0].name)
        assertTrue(parsed.ccService!![0].enabled)
        assertEquals(
            "https://push.example/send",
            parsed.ccService!![0].har.log.entries[0].request.url
        )
    }

    /**
     * Gson builds this data class through Unsafe, so a payload missing a required String
     * leaves that property null despite its non-null type. This is pinned because it is
     * the reason `ConfigImport.validate` exists: `MainActivity.onActivityResult` reads
     * `jsonConfig.apiAddress.isNotEmpty()` off the parsed object, which a null turns into
     * an immediate crash rather than a message the user can act on.
     *
     * The parse behaviour asserted here has not changed; what changed is that nothing
     * downstream trusts it any more.
     */
    @Test
    fun missingRequiredStringDeserializesAsNull() {
        val parsed = gson.fromJson("""{"chat_id":"-100"}""", ScannerJson::class.java)
        val botToken: String? = parsed.botToken
        val apiAddress: String? = parsed.apiAddress
        assertNull(botToken)
        assertNull(apiAddress)
        assertEquals("-100", parsed.chatId)
        assertFalse(parsed.batteryMonitoringSwitch) // primitives fall back to their zero value
    }
}
